clean:
	cd `pwd`/2/2.1; \
	make clean
	cd `pwd`/2/2.2; \
	make clean
	cd `pwd`/3/3.1; \
	make clean
	cd `pwd`/4/4.1; \
	make clean
	cd `pwd`/5/5.1; \
	make clean
	cd `pwd`/5/5.2; \
	make clean
	cd `pwd`/6/6.1; \
	make clean
	cd `pwd`/7/7.1; \
    make clean
	cd `pwd`/8/8.1; \
	make clean
	cd `pwd`/9/9.1; \
	make clean
